Update `rails` dependency
elainenaomi/hello-rails pull request #1
Opened 2019-03-29 05:11 UTC by elainenaomi

2019-03-29 05:17 UTC, elainenaomi commented on Gemfile
> +gem 'rails', '~> 5.1.6'
✂️

2019-03-29 05:17 UTC, elainenaomi commented on Gemfile
> +gem 'sqlite3'
✂️

2019-03-29 05:17 UTC, elainenaomi commented on Gemfile
> +gem 'puma', '~> 3.7'
✂️

2019-03-29 05:17 UTC, elainenaomi commented on Gemfile
> +gem 'sass-rails', '~> 5.0'
✂️

2019-03-29 05:17 UTC, elainenaomi commented on Gemfile
> +gem 'uglifier', '>= 1.3.0'
✂️

2019-04-02 04:41 UTC, random-person-123 requested changes
🤢

2019-04-04 07:45 UTC, random-person-123 commented on Gemfile
> +gem 'rails', '~> 5.1.6'
✂️

2019-05-16 02:46 UTC, closed without merging